Coursework/WebApp/Models/User/UserInfo.cs
using CourseworkDB.Model;
using System.Collections.Generic;

namespace WebApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public bool IsDelete { get; set; }
        public Role Role { get; set; }
        public ICollection<Message> Messages { get; set; }
        public ICollection<RoomInfo> Rooms { get; set; }
        public ICollection<Payment> Payments { get; set; }

    }
}

Coursework/WebApp/Controllers/UserController.cs
using CourseworkDB.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService, IRoomService roomService)
        {
            _userService = userService;
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult GetAll()
        {
            var users = _userService.GetAll();
            var model = new List<UserInfo>();

            model = users
                .Select(u => new UserInfo
                {
                    Id = u.Id,
                    Firstname = u.Firstname,
                    Lastname = u.Lastname,
                    Email = u.Email,
                    Role = new Role
                    {
                        Name = u.Role.Name,

                    },
                    IsDelete = u.IsDelete,
                }).ToList();
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GetAccount(int id)
        {
            string userId = User.FindFirst(x => x.Type == ClaimTypes.UserData).Value;
            id = Convert.ToInt32(userId);

            var user = _userService.Get(id);
            var model = new UserInfo
            {
                Id = user.Id,
                Firstname = user.Firstname,
                Lastname = user.Lastname,
                Email = user.Email,
                Adress = user.Adress,
                Phone = user.Phone,
                Password = user.Password,
                Role = user.Role,
            };
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GetInfo(int id)
        {
            var user = _userService.Get(id);
            var model = new UserInfo
            {
                Id = user.Id,
                Firstname = user.Firstname,
                Lastname = user.Lastname,
                Email = user.Email,
                Adress = user.Adress,
                Phone = user.Phone,
                Password = user.Password,
            };
            return View(model);
        }


        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult Update(UserInfo newUser)
        {
            string userId = User.FindFirst(x => x.Type == ClaimTypes.UserData).Value;
            var Id = Convert.ToInt32(userId);

            var user = _userService.Get(Id);

            user.Firstname = newUser.Firstname;
            user.Lastname = newUser.Lastname;
            user.Phone = newUser.Phone;
            user.Adress = newUser.Adress;

            _userService.Update(user);

            return Redirect("/User/GetAccount");
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult Delete(int number)
        {
            bool result = false;

            var user = _userService.Get(number);
            if (user != null)
            {
                _userService.Delete(user);
                result = true;
            }

            return Json(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Recovery(UserInfo recUser)
        {
            bool result = false;

            var user = _userService.Get(recUser.Id);

            if (user != null)
            {
                user.IsDeleted = recUser.IsDelete;
                _userService.Update(user);
                result = true;
            }
            return Json(result);
        }
    }
}

Coursework/WebApp/Views/User/GetAccount.cshtml
@using WebApp.Models
@model UserInfo

<div>
    <form asp-action="Update" asp-controller="User">
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        <img class="rounded-circle mt-5" style="width:150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg">
                        <span class="font-weight-bold">@Model.Firstname</span>
                        <span class="text-black-50">@Model.Email</span>
                        <span> </span>
                    </div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Profile Settings</h4>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6">
                                <label class="labels" asp-for="Firstname">Name</label>
                                <input type="text" asp-for="Firstname" class="form-control" placeholder="@Model.Firstname" value="@Model.Firstname">
                                <span asp-validation-for="Firstname" />
                            </div>

                            <div class="col-md-6">
                                <label class="labels" asp-for="Lastname">Surname</label>
                                <input type="text" asp-for="Lastname" class="form-control" value="@Model.Lastname" placeholder="@Model.Lastname">
                                <span asp-validation-for="Lastname" />
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="col-md-12">
                                <label class="labels" asp-for="Phone">Mobile Number</label>
                                <input type="text" asp-for="Phone" class="form-control" placeholder="@Model.Phone" value="@Model.Phone">
                                <span asp-validation-for="Phone" />
                            </div>

                            <div class="col-md-12">
                                <label class="labels" asp-for="Adress">Address</label>
                                <input type="text" asp-for="Adress" class="form-control" placeholder="@Model.Adress" value="@Model.Adress">
                                <span asp-validation-for="Adress" />
                            </div>

                        </div>
                    </div>
                    <div class="mt-5 text-center" style="align-content:center">
                        <button class="btn btn-primary profile-button" type="submit" id="btnsubmit">Save Profile</button>
                        @*@Html.ActionLink("Delete Profile", "Delete", "User", new { Id = Model.Id }, new { id = "btndelete", type = "button", @class = "btn btn-primary profile-button" })*@
                        <button class="btn btn-primary profile-button" type="button" id="btndelete">Delete Profile</button>
                    </div>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </form>
</div>



@section Scripts
{
    <script>
        $(document).ready
            (
                $('#btnsubmit').click(
                    function () {
                        window.location.href="/User/GetAccount";
                    }
                ),

                  $('#btndelete').click(
                      function () {

                          var id = @Model.Id;

                          $.ajax({
                              type: "POST",
                              url: "@Url.Action("Delete", "User")",
                              data: {
                                  number: id,
                              },
                              success: function (result)
                              {
                                  if (result) {
                                      alert("Success");
                                      window.location.href = "/Account/Logout";
                                  }
                                  else { alert("Failed!"); }
                              }
                          })
                      }
                  )
            );
    </script>
}

Coursework/WebApp/Views/User/GetAll.cshtml
@using WebApp.Models
@model List<UserInfo>

    <table class="table table-striped" style=" text-align:center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-at" viewBox="0 0 16 16">
                        <path d="M13.106 7.222c0-2.967-2.249-5.032-5.482-5.032-3.35 0-5.646 2.318-5.646 5.702 0 3.493 2.235 5.708 5.762 5.708.862
                              0 1.689-.123 2.304-.335v-.862c-.43.199-1.354.328-2.29.328-2.926 0-4.813-1.88-4.813-4.798 0-2.844 1.921-4.881 4.594-4.881
                              2.735 0 4.608 1.688 4.608 4.156 0 1.682-.554 2.769-1.416 2.769-.492 0-.772-.28-.772-.76V5.206H8.923v.834h-.11c-.266-.595-.881-.964-1.6-.964-1.4 0-2.378
                              1.162-2.378 2.823 0 1.737.957 2.906 2.379 2.906.8 0 1.415-.39 1.709-1.087h.11c.081.67.703 1.148 1.503 1.148 1.572 0 2.57-1.415 2.57-3.643zm-7.177.704c0-1.197.54-1.907
                              1.456-1.907.93 0 1.524.738 1.524 1.907S8.308 9.84 7.371 9.84c-.895 0-1.442-.725-1.442-1.914z" />
                    </svg>
                    Email
                </th>
                <th scope="col">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                        <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717
                              0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6
                              0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92
                              10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
                    </svg>
                    First
                </th>
                <th scope="col">Last</th>
                <th scope="col">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
                        <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16
                              1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0
                              14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z" />
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                    </svg>
                    Role
                </th>
                <th scope="col">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293
                              8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                    </svg>
                    Deleted
                </th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @{var i = 1;}

            @foreach (var user in Model)
            {

                <tr>
                    <th scope="row">@i</th>
                    <td>@user.Email</td>
                    <td>@user.Firstname</td>
                    <td>@user.Lastname</td>
                    <td>@user.Role.Name</td>
                    <td>@user.IsDelete</td>
                    @if (user.IsDelete == false)
                    {
                        <td>
                            <a href="#" style=" min-width: 90px;" class="btn btn-outline-dark" data-toggle="modal" data-target="#deleteModal" id="delModal" onclick="Confirm(@user.Id)"> Delete </a>
                        </td>
                    }
                    else
                    {
                        <td>
                            <a href="#" style=" min-width: 90px;" class="btn btn-outline-dark" data-toggle="modal" data-target="#recModal" id="recModalLa" onclick="ConfirmRec(@user.Id)">Recovery</a>
                        </td>
                    }
                    <td>
                        @Html.ActionLink("More info", "GetAccount", "User", new { Id = user.Id }, new { type = "button", @class = "button" })
                    </td>
                </tr>
                i++;
            }

        </tbody>
    </table>

    <input type="hidden" id="roomId" />

    <!--Delete-->
    <div class="modal fade" id="deleteModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Confirm</h2>
                </div>
                <div class="modal-body">
                    <h3>Are you want to delete this account?</h3>
                </div>
                <div class="modal-footer">
                    <div class="btn-group">
                        <a href="#" id="btnDelete" class="" style="margin-right:10px">Delete</a>
                        <a href="#" id="btnCancelDelete" class="" data-dismiss="modal" aria-label="Close">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End-->
    <!--Restore-->
    <div class="modal fade" id="recModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Confirm</h2>
                </div>
                <div class="modal-body">
                    <h3>Are you want to recovery this account?</h3>
                </div>
                <div class="modal-footer">
                    <div class="btn-group">
                        <a href="#" id="btnRec" class="" style="margin-right:10px">Recovery</a>
                        <a href="#" id="btnCancelRec" class="" data-dismiss="modal" aria-label="Close">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End-->

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#btnDelete").click(function () {

                var id = $("#roomId").val();

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "User")",
                    data:
                    {
                        number: id,
                    },
                    success: function (result) {

                        if (result) {
                            $("#deleteModal").modal("hide");
                            $("#roomId").val(null);
                            window.location.reload();
                        }
                        else { alert("Failed!"); }
                    }
                });
            });


            $("#btnRec").click(function () {

                var i = $("#roomId").val();
                var del = false;

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Recovery", "User")",
                    data:
                    {
                        Id: i,
                        IsDeleted: del,
                    },
                    success: function (result) {

                        if (result) {
                            $("#recModal").modal("hide");
                            $("#roomId").val(null);
                            window.location.reload();
                        }
                        else { alert("Failed!"); }
                    }
                });
            });
        });


        var Confirm = function (id) {
            $("#roomId").val(id);
            //$("#deleteModal").modal("show");
        }

        var ConfirmRec = function (id) {
            $("#roomId").val(id);
           // $("#recModal").modal("show");
        }

    </script>
}

Coursework/WebApp/Views/User/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}