Coursework/WebApp/Models/Room/BufferImage.cs
using Microsoft.AspNetCore.Http;

namespace WebApp.Models.Room
{
    public class BufferImage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IFormFile picFile { get; set; }
        public byte[] Image { get; set; }
        public int RoomId { get; set; }
    }
}

Coursework/WebApp/Models/Room/RoomInfo.cs
using CourseworkDB.Model;
using System.Collections.Generic;

namespace WebApp.Models
{
    public class RoomInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Adress { get; set; }
        public string Owner { get; set; }
        public decimal ActualPrice { get; set; }
        public string Desc { get; set; }
        public List<Picture> Pictures { get; set; }
       // public ICollection<Reservation> Reservations { get; set; }
       // public ICollection<Message> Messages { get; set; }
    }
}

Coursework/WebApp/Controllers/ReservationController.cs
using AutoMapper;
using CourseworkDB.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;
        private readonly IUserService _userService;
        private readonly IRoomService _roomService;
        public ReservationController(IReservationService reservationService, IUserService userService, IRoomService roomService)
        {
            _reservationService = reservationService;
            _userService = userService;
            _roomService = roomService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetAll()
        {

            var res = _reservationService.GetAll();
            var model = new List<ReservationInfo>();

            model = res
                .Select(u => new ReservationInfo
                {
                    Id = u.Id,
                    Adress = u.Room.Adress,
                    Room = u.Room.Name,
                    Firstname = u.Client.Firstname,
                    Lastname = u.Client.Lastname,
                    StartTime = u.StartTime,
                    EndTime = u.EndTime,
                })
            .ToList();

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GetUserAll()
        {
            string userId = User.FindFirst(x => x.Type == ClaimTypes.UserData).Value;
            var id = Convert.ToInt32(userId);


            var res = _reservationService.GetAll().Where(i => i.Client.Id == id).ToList();
            var model = new List<ReservationInfo>();

            model = res
                .Select(u => new ReservationInfo
                {
                    Id = u.Id,
                    Adress = u.Room.Adress,
                    Room = u.Room.Name,
                    Firstname = u.Client.Firstname,
                    Lastname = u.Client.Lastname,
                    StartTime = u.StartTime,
                    EndTime = u.EndTime,
                })
            .ToList();

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GetInfo(int id)
        {
            var res = _reservationService.Read(id);
            var model = new ReservationInfo()
            {
                Id = res.Id,
                Adress = res.Room.Adress,
                Room = res.Room.Name,
                Firstname = res.Client.Firstname,
                Lastname = res.Client.Lastname,
                StartTime = res.StartTime,
                EndTime = res.EndTime,
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(ReservationInfo newReserv, int roomId, DateTime start, DateTime end )
        {
            string userId = User.FindFirst(x => x.Type == ClaimTypes.UserData).Value;
            var id = Convert.ToInt32(userId);

            var res = new Reservation()
            {
                Id = newReserv.Id,
                StartTime = start,
                EndTime = end,
                Client = _userService
                    .Get(id),
                Room = _roomService.Get(roomId)
            };

            _reservationService.Add(res);
            var result = true;

           return Json(result);
           //return Redirect(Url.Action("GetUserAll", "Reservation"));
        }
    }
}

Coursework/WebApp/Controllers/RoomController.cs
using CourseworkDB.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using WebApp.Models;
using WebApp.Models.Room;

namespace WebApp.Controllers
{
    public class RoomController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoomService _roomService;
        private readonly IPictureService _pictureService;

        public RoomController(IUserService userService, IRoomService roomService, IPictureService pictureService)

        {
            _userService = userService;
            _roomService = roomService;
            _pictureService = pictureService;
        }

        [HttpGet]
        public IActionResult GetInfo(int id)
        {
            var room = _roomService.Get(id);
            var model = new RoomInfo()
            {
                Id = room.Id,
                Name = room.Name,
                Adress = room.Adress,
                ActualPrice = room.ActualPrice,
                Desc = room.Desc,
                Pictures = _pictureService.GetPicRoom(id),
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var room = _roomService.GetAll();
            var model = new List<RoomInfo>();

            model = room
                .Select(u => new RoomInfo
                {
                    Id = u.Id,
                    Adress = u.Adress,
                    Name = u.Name,
                    ActualPrice = u.ActualPrice,
                    Desc = u.Desc,
                    Owner = u.Owner.Lastname,
                    Pictures = _pictureService.GetPicRoom(u.Id),
                })
            .ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult Create(RoomInfo updRoom)
        {

            var id = Convert
                .ToInt32
                (User
                .FindFirst(x => x.Type == ClaimTypes.UserData)
                .Value);

            var room = new Room()
            {
                Serial = _roomService.RandomSerial(),
                Name = updRoom.Name,
                Adress = updRoom.Adress,
                ActualPrice = updRoom.ActualPrice,
                Desc = updRoom.Desc,

                Owner = _userService.Get(id),
            };

            _roomService.Add(room);
            return RedirectToAction("GetUserAll");
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult Update(RoomInfo room)
        {
            var result = false;

            var updRoom = _roomService.Get(room.Id);

            updRoom.Name = room.Name;
            updRoom.Adress = room.Adress;
            updRoom.ActualPrice = room.ActualPrice;
            updRoom.Desc = room.Desc;

            if (updRoom != null)
            {
                result = true;
                _roomService.Update(updRoom);

            }

            return Json(result);
        }

        public IActionResult GetUserAll()
        {
            var id = Convert
                .ToInt32
                (User
                .FindFirst(x => x.Type == ClaimTypes.UserData)
                .Value);

            var room = _roomService.GetAll().Where(i => i.Owner.Id == id).ToList();
            var model = new List<RoomInfo>();

            model = room
                .Select(u => new RoomInfo
                {
                    Id = u.Id,
                    Adress = u.Adress,
                    Name = u.Name,
                    ActualPrice = u.ActualPrice,
                    Desc = u.Desc,
                    Owner = u.Owner.Lastname,
                    Pictures = _pictureService.GetPicRoom(u.Id).ToList(),
                })
            .ToList();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        public IActionResult Delete(int id)
        {
            bool result = false;

            var room = _roomService.Get(id);
            if (room != null)
            {
                _roomService.Delete(room);
                result = true;
            }

            return Json(result);
        }


        [HttpGet]
        public IActionResult GetFree(DateTime st, DateTime et)
        {
            var room = _roomService.GetFree(st, et);
            var model = new List<RoomInfo>();
            model = room
                .Select(u => new RoomInfo
                {
                    Id = u.Id,
                    Adress = u.Adress,
                    Name = u.Name,
                    ActualPrice = u.ActualPrice,
                    Owner = u.Owner.Lastname,
                    Pictures = _pictureService.GetPicRoom(u.Id).ToList(),
                })
            .ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult SaveImg()
        {
            return View();
        }


        [HttpPost]
        public IActionResult SaveImg(BufferImage img)
        {
            //var result = false;

            var pic = new Picture { Name = img.Name };

            byte[] imageData = null;
            //object in byte
            using (var binaryReader = new BinaryReader(img.picFile.OpenReadStream()))
            {
                imageData = binaryReader.ReadBytes((int)img.picFile.Length);
            }

            pic.File = imageData;
            pic.Room = _roomService.Get(img.RoomId);
           
            //if (pic.File != null)
            //{
            //    result = true;
            //}

            _pictureService.Save(pic);

            var id = Convert
                            .ToInt32
                            (User
                            .FindFirst(x => x.Type == ClaimTypes.UserData)
                            .Value);

            var room = _roomService.GetAll().Where(i => i.Owner.Id == id).ToList();
            var model = new List<RoomInfo>();

            model = room
                .Select(u => new RoomInfo
                {
                    Id = u.Id,
                    Adress = u.Adress,
                    Name = u.Name,
                    ActualPrice = u.ActualPrice,
                    Desc = u.Desc,
                    Owner = u.Owner.Lastname,
                    Pictures = _pictureService.GetPicRoom(u.Id).ToList(),
                })
            .ToList();

            //return Json(result);
            return View("GetUserAll", model);
        }

        [HttpGet]
        public IActionResult GetImage(int id)
        {

            var img = _pictureService
                .GetPicRoom(id).
                ToList();

            var model = new List<BufferImage>();

            model = img.Select(u => new BufferImage
            {
                Name = u.Name,
                Image = u.File,
                Id = u.Id,

            }).ToList();

            return View(model);
        }

    }
}

Coursework/WebApp/Views/Room/GetAll.cshtml
@using WebApp.Models
@model List<RoomInfo>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">




</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <section class="rooms-section spad">
        <div class="container">
            <div class="row">
                @foreach (var room in Model)
                {
                    <div class="col-lg-4 col-md-6">
                        <div class="room-item">
                            @if (room.Pictures.Count == 0)
                            {
                                <img src="~/pictures/room/no_image.jpg" style="width: 360px; height: 233.51px; border: 1px solid #ebebeb;"/>
                            }
                            else
                            {
                                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(room.Pictures.First().File))" style="width: 360px; height: 233.51px;"/>
                            }
                            <div class="ri-text">
                                <h4>@room.Name</h4>
                                <h3>@room.ActualPrice<span>/Pernight</span></h3>
                                <a href="#">@Html.ActionLink("More detais", "GetInfo", "Room", new { Id = room.Id }, new { type = "button", @class = "primary-btn" })</a>
                            </div>
                        </div>
                    </div>
                 }
            </div>
        </div>
    </section>

    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>

Coursework/WebApp/Views/Room/GetFree.cshtml
@using WebApp.Models
@model List<RoomInfo>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">




</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <section class="rooms-section spad">
        <div class="container">
            <div class="row">
                @foreach (var room in Model)
                {
                    <div class="col-lg-4 col-md-6">
                        <div class="room-item">
                            @if (room.Pictures.Count == 0)
                            {
                                <img src="~/pictures/room/no_image.jpg" style="width: 360px; height: 233.51px; border: 1px solid #ebebeb;" />
                            }
                            else
                            {
                                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(room.Pictures.First().File))" style="width: 360px; height: 233.51px;" />
                            }
                            <div class="ri-text">
                                <h4>@room.Name</h4>
                                <h3>@room.ActualPrice<span>/Pernight</span></h3>
                                <p class="primary-btn">@Html.ActionLink("More detais", "GetInfo", "Room", new { Id = room.Id }, new { type = "button", @class = "button" })</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>

    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>

Coursework/WebApp/Views/Room/GetImage.cshtml
@using WebApp.Models.Room
@model List<BufferImage>


@foreach (var model in Model)
{
    <img src="data:image/jpeg;base64,@(Convert.ToBase64String(model.Image))"/>
};

Coursework/WebApp/Views/Room/GetInfo.cshtml
@using WebApp.Models
@model RoomInfo

<!DOCTYPE html>

<head>
    <!--Google Font-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">
    <!--Css Styles-->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/flaticon.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Room Details Section Begin -->
    <section class="room-details-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="room-details-item">
                        <div id="carouselRoom" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @if (Model.Pictures.Count == 0)
                                {
                                    <img src="~/pictures/room/no_image.jpg" style="width: 770px; height: 440px; border: 1px solid #ebebeb;" />
                                }
                                else
                                {
                                    <div class="carousel-item active">
                                        <img class="img-fluid" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Pictures.First().File))" style="width:770px; height:440px;">
                                    </div>

                                    @for (var pic = 1; pic < Model.Pictures.Count; pic++)
                                    {

                                        <div class="carousel-item">
                                            <img class="img-fluid" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Pictures[pic].File))" style="width:770px; height:440px;">
                                        </div>
                                    }
                                }
                            </div>
                            <a class="carousel-control-prev" href="#carouselRoom" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselRoom" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>

                        <div class="rd-text">
                            <div class="rd-title">
                                <div class="rdt-right">
                                    <div class="rating">
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star-half_alt"></i>
                                    </div>
                                </div>
                            </div>
                            <h2>@Model.ActualPrice<span>/Pernight</span></h2>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 5</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <p class="f-para">
                                Motorhome or Trailer that is the question for you. Here are some of the
                                advantages and disadvantages of both, so you will be confident when purchasing an RV.
                                When comparing Rvs, a motorhome or a travel trailer, should you buy a motorhome or fifth
                                wheeler? The advantages and disadvantages of both are studied so that you can make your
                                choice wisely when purchasing an RV. Possessing a motorhome or fifth wheel is an
                                achievement of a lifetime. It can be similar to sojourning with your residence as you
                                search the various sites of our great land, America.
                            </p>
                            <p>
                                The two commonly known recreational vehicle classes are the motorized and towable.
                                Towable rvs are the travel trailers and the fifth wheel. The rv travel trailer or fifth
                                wheel has the attraction of getting towed by a pickup or a car, thus giving the
                                adaptability of possessing transportation for you when you are parked at your campsite.
                            </p>
                        </div>
                    </div>

                </div>

                <div class="col-lg-4">
                    <div class="room-booking">
                        <h3>Your Reservation</h3>
                        <form action="#" data-ajax="true" data-ajax-method="POST">
                            <div class="check-date">
                                <label for="date-in">Check In:</label>
                                <input type="text" class="date-input" id="date-in" autocomplete="off">
                                <i class="icon_calendar"></i>
                            </div>
                            <div class="check-date">
                                <label for="date-out">Check Out:</label>
                                <input type="text" class="date-input" id="date-out" autocomplete="off">
                                <i class="icon_calendar"></i>
                            </div>
                            @if ((User.Identity.IsAuthenticated))
                            {
                                <button class="reg" type="submit" id="@Model.Id">Booking now</button>
                            }
                            else
                            {
                                <button class="reg" type="button" id="not-authent">Booking now</button>
                            }
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </section>

    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <h4 class="alert-heading">Well done!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
            </div>
        </div>
    </div>>






    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>

</body>

@section Scripts
{

    <script>
        $(document).ready(function () {

        var roomid = null;
        var dstart = null;
        var dend = null;

        $(".reg").click(function () {

            roomid = $(this).attr("id");
            dstart = $('#date-in').val();
            dend = $('#date-out').val();

            $.ajax({
                    url: "@Url.Action("Create", "Reservation")",
                    async: true,
                    type: "POST",
                    //dataType: "http",
                    data:
                    {
                        roomId: roomid,
                        start: dstart,
                        end: dend,
                    },
                    success: function (result)
                    {
                        if (result)
                        {
                            $("#myModal").modal("show");
                            //window.location.reload();
                        }

                    },
            });
        });

            $("#not-authent").click(function () {
                alert("Please authorise to submit your order.");
            })

        })
    </script>
}

Coursework/WebApp/Views/Room/SaveImg.cshtml
@using WebApp.Models.Room
@model BufferImage


<form asp-action="SaveImg" asp-controller="Room" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="exampleFormControlFile1">Example file input</label>
        <input name="picFile" type="file" class="form-control-file" id="exampleFormControlFile1">
    </div>
    <input type="submit" value="Добавить" />
</form>

<a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="GetImage">Picture</a>


@*<p>
    <label>Имя</label>
    <input name="Name" class="form-control" />
</p>
<p>
    <label>Image</label>
    <input name="file" type="file" class="form-control-file" />
</p>
<p>
    <input type="submit" value="Добавить" />
</p>*@